# Generated by Django 4.2.1 on 2023-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0003_risk_score_risk_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
