# Generated by Django 4.2.1 on 2023-05-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0004_alter_risk_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplyMetric',
            new_name='RiskMetric',
        ),
        migrations.DeleteModel(
            name='DemandMetric',
        ),
    ]
