# Generated by Django 4.2.1 on 2023-05-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0005_rename_supplymetric_riskmetric_delete_demandmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskmetric',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='value',
        ),
        migrations.AlterField(
            model_name='riskmetric',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RiskMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('risk_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_monitor.riskmetric')),
            ],
        ),
    ]
