# Generated by Django 4.2.1 on 2023-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0006_remove_riskmetric_timestamp_remove_riskmetric_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmetric',
            name='setpoint',
            field=models.FloatField(default=0.0),
        ),
    ]
