# Generated by Django 4.2.1 on 2023-05-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0009_remove_risksubscription_email_risksubscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krivalue',
            name='kri',
        ),
        migrations.RemoveField(
            model_name='riskevent',
            name='risk_agent',
        ),
        migrations.DeleteModel(
            name='KRI',
        ),
        migrations.DeleteModel(
            name='KRIValue',
        ),
        migrations.DeleteModel(
            name='RiskAgent',
        ),
    ]
