# Generated by Django 4.2.1 on 2023-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0010_remove_krivalue_kri_remove_riskevent_risk_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='simulation_status',
            field=models.CharField(default='Off', max_length=255),
        ),
    ]
