# Generated by Django 4.2.1 on 2023-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0012_remove_risk_simulation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmetric',
            name='simulation_status',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
