# Generated by Django 4.2.1 on 2023-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0013_alter_riskmetric_simulation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='source',
            field=models.CharField(default='Network', max_length=255),
        ),
    ]
